# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "lhd" do |lhd|
    lhd.vm.hostname = "lhd"
    lhd.vm.box = "ubuntu/trusty64"
    lhd.vm.network "forwarded_port", guest: 80, host: 8080
    lhd.vm.network "public_network"
    lhd.vm.synced_folder "../project/", "/var/www/html", create: true
    lhd.vm.provider "virtualbox" do |vb|
      vb.name = "lhd"
    end

  config.vm.provision "shell", inline: <<-SHELL
    echo "Installing build essentials"
    sudo apt-get install -y build-essential

    echo "Start Installing LAMP"
    sudo locale-gen UTF-8 > /dev/null
    sudo apt-get install -y language-pack-en-base > /dev/null
    sudo LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php -y > /dev/null
    sudo apt-get -y update > /dev/null

    echo "Installing Apache"
    sudo apt-get -y install apache2 > /dev/null

    echo "Installing PHP"
    sudo apt-get -y install php7.0 php7.0-mysql  > /dev/null # mod_php
    echo '<?php phpinfo(); ?>' | sudo tee --append /var/www/html/info.php  > /dev/null

    sudo apt-get -y install curl git

    echo "Installing MySQL"
    DBPASSWD=abc123
    echo "mysql-server mysql-server/root_password password $DBPASSWD" | debconf-set-selections  > /dev/null
    echo "mysql-server mysql-server/root_password_again password $DBPASSWD" | debconf-set-selections  > /dev/null
    sudo apt-get -y install mysql-server  > /dev/null

    sudo service apache2 restart > /dev/null
    echo "Finish Installing LAMP!!!"

    echo "Importing database"
    # mysql -u root --password="abc123" < /var/www/html/src/dhcpadmin/sql/ddl.sql

    sudo bash -c "echo 'www-data ALL=NOPASSWD: ALL' >> /etc/sudoers"
  SHELL
  end

end
